### ISSUE TITLE
Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.CodeAnalysisReporting#25]
So addin can be loaded from Cake CoreCLR runner

**Comment by RLittlesII** [comment]
@gep13 @pascalberger 
.NET dropped `System.Xml.Xsl` namespace and with it support for XsltCompiledTransform in netstandard 1.6 (probably earlier).  

`System.Xml.Xsl` was added back in netstandard 2.0.

Is there another way to transform XSLT that we can use for netstandard 1.6 that either of you are aware of?  Targeting net standard 2.0 is not an option.

Suggestions?

**Comment by pascalberger** [comment]
@RLittlesII I'm not sure if it is worth to migrate this to netstandard, since I plan to deprecate this addin anyway in favor of the Cake.Issues.Reporting.Generic addin (see #24), which would give a much better approach for issue reporting and doesn't use XSLT. The main open issue with Cake.Issues.Reporting.Generic is embedding of the required assemblies (https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/issues/5).

**Comment by RLittlesII** [comment]
@pascalberger That's fine.  I created an issue to track removing the dependency from Cake.Recipe https://github.com/cake-contrib/Cake.Recipe/issues/157
